### ISSUE TITLE
Do a [Data Camp on Seaborn](https://campus.datacamp.com/courses/introduction-to-data-visualization-with-seaborn)

### ISSUE THREAD

**Issue by missKatiaPunter** [graceuche/northeastern-final-project#12]
If you could do this Technical Spike @graceuche and pin your certificate here, it will look good.

**Comment by graceuche** [comment]
<img width="657" alt="image" src="https://user-images.githubusercontent.com/99759783/167930482-c3690033-6a3b-49b2-becd-b136f5bba1ea.png">
